#!/usr/bin/env python

import argparse
import asyncio

from check_ctf import get_url, show_prev_events
from common import colors
from find_writeups import original_writeups


async def main():
    """Main function to handle all the process
    """
    parser = argparse.ArgumentParser(description="Easily get those precious writeups")

    maingroup = parser.add_argument_group(title='required any one of them')

    group = maingroup.add_mutually_exclusive_group(required=True)
    group.add_argument("-n", "--name", help="search for writeups by CTF name")
    group.add_argument("-l", "--link", help="search for writeups by CTF url")
    group.add_argument("-r", "--random", help="Show last 10 CTF",  action='store_true')
    args = parser.parse_args()

    if args.random:
        url = await show_prev_events()
        writeups = await original_writeups(url)
        print(colors(writeups, 32))

    # when a direct link to tasks is given
    if args.link and args.link.endswith('tasks/'):
        writeups = await original_writeups(args.link)
        print(colors(writeups, 32))

    # When a name of the event is given
    if args.name:
        tasks = await get_url(args.name)
        if tasks:
            writeups = await original_writeups(tasks)
            if writeups:
                print(colors(writeups, 32))


if __name__ == "__main__":
    LOOP = asyncio.get_event_loop()
    LOOP.run_until_complete(main())
